version: '2'
services:
  redis:
    image: redis:3-alpine
  web:
    build: .
    command: bundle exec unicorn
    ports:
      - 9240:9240
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis/0
    volumes:
      - /colore/storage
  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml -r ./lib/sidekiq_app.rb
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis/0
    volumes_from:
      - web:rw
