source 'https://rubygems.org'

gem 'unicorn'
gem 'thin'
gem 'json'
gem 'ruby-filemagic'
gem 'mime-types'
gem 'haml'
gem 'sinatra'
gem 'iso-639'
gem 'wkhtmltopdf'
gem 'sidekiq'
gem 'sidetiq'
gem 'rest-client'
gem 'mail'

gem 'rake'
gem 'rspec'
gem 'yard'
gem 'rack-test'
gem 'simplecov'
gem 'byebug'
gem 'timecop'
#gem 'api-config', git: 'http://code.ifad.org/api-config'
